version: "3"

services:
    reddit-discord-feed:
        build: .
        restart: unless-stopped
        volumes:
            - ./config.toml:/code/config.toml
            - ./cronfile:/etc/cron.d/feed_cron
