name: Build Release

on:
  release:
    types: [published]
  workflow_dispatch:  
    inputs:
      tag_name:
        description: "Tag name of the release"
        required: true
# push:
#   branches:
#     - main
      

env:
  CARGO_TERM_COLOR: always
  TAG_NAME: ${{ github.event.release.tag_name || github.event.inputs.tag_name }}

jobs:
  build:

    permissions:
      contents: write  
    strategy:
      matrix:
        cargo_target: [release]
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            bin_name: pixelsortery-linux
          - os: macos-latest
            target: x86_64-apple-darwin
            bin_name: pixelsortery-darwin
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            bin_name: pixelsortery-windows
    runs-on: ${{ matrix.os }}
    name: Build for ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    - name: Show Rustup Info
      run: rustup show
      
    - name: Cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        
    - name: Build Binaries in mode "${{ matrix.cargo_target }}" for os "${{ matrix.os }}"
      run: cargo build --profile ${{ matrix.cargo_target }} # --target ${{ matrix.target}}
    # - name: Run tests
    #   run: cargo test --profile ${{ matrix.BUILD_TARGET }}
    - name: Rename Binary with Version
      run: |
        if [[ "$RUNNER_OS" == "Windows" ]] ; then EXT=".exe"; fi
        mv   target/${{ matrix.cargo_target }}/reddit-discord-feed$EXT  ${{ matrix.bin_name }}-${{ env.TAG_NAME }}$EXT
          
    - name: Release
      uses: softprops/action-gh-release@v2
      # if: startsWith(github.ref, 'refs/tags/')
      with:
        tag_name: ${{ env.TAG_NAME }}
        files:  feed-${{ env.TAG_NAME }}
        
