name: Build Release

on:
  release:
    types: [published]
  workflow_dispatch:  
    inputs:
      tag_name:
        description: "Tag name of the release"
        required: true
# push:
#   branches:
#     - main
      

env:
  CARGO_TERM_COLOR: always
  TAG_NAME: ${{ github.event.release.tag_name || github.event.inputs.tag_name }}

jobs:
  build:

    permissions:
      contents: write  
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            bin_name: feed-linux
            cargo_target: release
          - os: macos-latest
            target: x86_64-apple-darwin
            bin_name: feed-darwin-x86
            cargo_target: release
          - os: macos-latest
            target: aarch64-apple-darwin
            bin_name: feed-darwin
            cargo_target: release
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            bin_name: feed-windows
            cargo_target: release
    runs-on: ${{ matrix.os }}
    name: Build for ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
      with: 
        ref: ${{ env.TAG_NAME }}
    - name: Show Rustup Info
      run: rustup show
      
    - name: Cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Install Rust and Add x86_64 Target
      run: |
          rustup update stable
          rustup default stable-${{ matrix.target }}
    
    - name: Build Binaries in mode "${{ matrix.cargo_target }}" for os "${{ matrix.os }}"
      run: cargo build --profile ${{ matrix.cargo_target }} --target ${{ matrix.target }}
    # - name: Run tests
    #   run: cargo test --profile ${{ matrix.BUILD_TARGET }}
    - name: Rename Binary with Version
      shell: bash
      run: |
        if [[ "$RUNNER_OS" == "Windows" ]] ; then EXT=".exe"; fi
        src=target/${{ matrix.target }}/${{ matrix.cargo_target }}/reddit-discord-feed$EXT
        dst=${{ matrix.bin_name }}-${{ env.TAG_NAME }}$EXT
        mv  "$src" "$dst"
        echo "BIN_NAME=$dst" >> $GITHUB_ENV
          
    - name: Upload Artifacts to Release
      uses: softprops/action-gh-release@v2
      # if: startsWith(github.ref, 'refs/tags/')
      with:
        tag_name: ${{ env.TAG_NAME }}
        files:  ${{ env.BIN_NAME }}
        
