name: Build Release

on:
  release:
    types: [published]
  workflow_dispatch:  
    inputs:
      tag_name:
        description: "Tag name of the release"
        required: true
# push:
#   branches:
#     - main
      

env:
  CARGO_TERM_COLOR: always
  TAG_NAME: ${{ github.event.release.tag_name || github.event.inputs.tag_name }}

jobs:
  build-linux:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        BUILD_TARGET: [release]
        
    steps:
    - uses: actions/checkout@v4
    - name: Show Rustup Info
      run: rustup show
      
    - name: Cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        
    - name: Build Binaries in mode "${{ matrix.BUILD_TARGET }}"
      run: cargo build --profile ${{ matrix.BUILD_TARGET }}
    # - name: Run tests
    #   run: cargo test --profile ${{ matrix.BUILD_TARGET }}
    - name: Rename Binary with Version
      run: mv target/${{ matrix.BUILD_TARGET }}/reddit-discord-feed target/${{ matrix.BUILD_TARGET }}/feed-${{ env.TAG_NAME }}
        
    - name: Upload artifact to Release
      uses: softprops/action-gh-release@v2.2.1
      with:
        name: feed-${{ env.TAG_NAME }}
        files: target/${{ matrix.BUILD_TARGET }}/feed-${{ env.TAG_NAME }}
        tag_name: ${{ env.TAG_NAME }}  # Use the tag from the release event
        overwrite: true  # Replace existing files if needed

        
